name: CI

on: [push]

jobs:
  e2e-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ci/e2e-kubeval.sh app-kubernetes
      - uses: engineerd/setup-kind@v0.1.0
      - run: ci/e2e-flagger.sh
      - run: ci/e2e-test.sh app-kubernetes
      - if: failure()
        run: ci/e2e-logs.sh
  e2e-linkerd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ci/e2e-kubeval.sh app-linkerd
      - uses: engineerd/setup-kind@v0.1.0
      - run: ci/e2e-linkerd.sh
      - run: ci/e2e-flagger.sh linkerd
      - run: ci/e2e-test.sh app-linkerd
      - if: failure()
        run: ci/e2e-logs.sh linkerd
  e2e-istio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ci/e2e-kubeval.sh app-istio
      - uses: engineerd/setup-kind@v0.1.0
      - run: ci/e2e-istio.sh
      - run: ci/e2e-flagger.sh istio
      - run: ci/e2e-test.sh app-istio
      - if: failure()
        run: ci/e2e-logs.sh istio